# Generated by Django 3.2.11 on 2022-04-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='New York', max_length=180, verbose_name='city'),
        ),
    ]
