# Generated by Django 3.2.11 on 2022-04-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='max_length',
            new_name='about_me',
        ),
    ]
